test: git push test -parkjiwon
3-9-teskify/project pull request #5
Opened 2024-01-20 15:08 UTC by bjiwon324

### 📌 작업 사항
---
- [test] git push test
- util 폴더 example 파일 삭제 후 index.ts 파일 추가

2024-01-20 15:34 UTC, rladngus133 commented
승인검토 체크

2024-01-20 15:37 UTC, rladngus133 approved these changes
승인 테스트입니다.

2024-01-20 15:38 UTC, rladngus133 requested changes
승인거부 테스트입니다
ex) 이부분은 수정을 해야할것 같은데요 ?

2024-01-20 15:59 UTC, bjiwon324 commented
이렇게 하는 거일까요?

2024-01-20 16:06 UTC, bjiwon324 commented
테스트

2024-01-25 01:48 UTC, rladngus133 approved these changes
승인테스트2

2024-01-25 02:31 UTC, merged